name: Deploy Jobs Function via Oryx (Python v1-decorators)

on:
  push:
    branches:
      - main
    paths:
      - 'backend/jobs/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './backend/jobs' # must be root where host.json is
  PYTHON_VERSION: '3.11'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FDEBE40C2C4346C99A4902ABC2F73BF5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_17A5FB42505F477DB8CFBBEDB8A8BF6D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EC44C02753DD470894762E10EDCF2515 }}

      - name: Deploy to Azure Functions using Oryx
        uses: Azure/functions-action@v1
        with:
          app-name: 'ehestifter-jobs'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          scm-do-build-during-deployment: true
          remote-build: true
          enable-oryx-build: true
