name: Deploy Telegram Bot to App Service

on:
  push:
    branches:
      - main
    paths:
      - 'backend/telegrambot/**'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  AZURE_WEBAPP_NAME: ehestifter-telegram-bot
  AZURE_RESOURCE_GROUP: eperi
  WORKDIR: backend/telegrambot

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Optional: run unit tests here

      - name: Oryx build artifact
        run: |
          mkdir -p ../artifact
          cp -r . ../artifact

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: artifact
