name: Build and deploy to Azure Function App - ehestiftercrud

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './backend/job_api'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DC688FC0B42649E0904CE91B342B7FCA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F8BBC68EF182457E86338E2B7F0AAD71 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AB6C1E299E2A4E9F9C848C6D06150D61 }}

      - name: Deploy to Azure Functions using Oryx
        uses: Azure/functions-action@v1
        with:
          app-name: 'ehestiftercrud'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
